version: "3"

services:
  envoy:
    image: envoyproxy/envoy:v1.21-latest
    container_name: envoy
    volumes:
      - "./configs:/etc/envoy"
    network_mode: "host"
    ports:
      - "9901:9901"
      - "8080:8080"
