apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "httpbinn-allow"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["GET", "HEAD"]
        paths: ["/bearer", "/get"]
    when:
    - key: request.auth.claims[cli]
      values: ["4Eu3RUjXtKFpKkqB0fvcvw"]