apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
 name: external-svc-httpbin
spec:
 hosts:
   - www.baidu.com
 location: MESH_EXTERNAL
 ports:
   - number: 80
     name: http
     protocol: HTTP
#  resolution: DNS
 resolution: STATIC # 静态
 endpoints:
   - address: 110.242.68.3
#  addresses:
#    - 110.242.68.3