apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
 name: httpbin
spec:
 hosts:
   - httpbin2.yanbo.svc.cluster.local
 location: MESH_EXTERNAL
 ports:
   - number: 8000
     name: http
     protocol: HTTP
#  resolution: DNS
 resolution: STATIC # 静态
 endpoints:
   - address: 172.16.26.242
#  addresses:
#    - 110.242.68.3