apiVersion: v1
kind: Secret
metadata:
  name: db-conn
  namespace: default
type: Opaque
stringData:
  endpoint: mysql.infra-system.svc.cluster.local
  port: "3306"
  password: admin
  username: root

---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: MySQLConnectionSecret
    connectionSecretRef:
      namespace: default
      name: db-conn
  # tls one of preferred(default), skip-verify, or true
  tls: preferred