apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample
spec:
  version: "v2.0.1"
  image: "saltbo/openfunction-sample-go-func:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder-go:latest
    env:
      FUNC_NAME: "HelloWorld"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      #url: "git@github.com:saltbo/openfunction-samples.git"
      url: "https://github.com/saltbo/openfunction-samples.git"
      sourceSubPath: "functions/knative/hello-world-go"
      revision: "e78ddf4"
  serving:
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent 
    runtime: "knative"
