# permissions for end users to view guestbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guestbook-viewer-role
rules:
- apiGroups:
  - webapp.saltbo.cn
  resources:
  - guestbooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.saltbo.cn
  resources:
  - guestbooks/status
  verbs:
  - get
