admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901

node:
  id: id_1
  cluster: test

static_resources:
  secrets:
  - name: token
    generic_secret:
      secret:
        inline_string: aaaaaan
  - name: hmac
    generic_secret:
      secret:
        inline_string: aavvcc

dynamic_resources:
  cds_config:
    path: /etc/envoy/cds.yaml
  lds_config:
    path: /etc/envoy/lds.yaml

# dynamic_resources:
#   cds_config:
#     api_config_source:
#       api_type: GRPC
#       grpc_services:
#         envoy_grpc:
#           cluster_name: xds_cluster
#   lds_config:
#     api_config_source:
#       api_type: GRPC
#       grpc_services:
#         envoy_grpc:
#           cluster_name: xds_cluster
# static_resources:
#   clusters:
#   - name: xds_cluster
#     connect_timeout: 0.25s
#     type: STRICT_DNS
#     lb_policy: ROUND_ROBIN
#     http2_protocol_options: {}
#     load_assignment:
#       cluster_name: xds_cluster
#       endpoints:
#       - lb_endpoints:
#         - endpoint:
#             address:
#               socket_address:
#                 address: docker.for.mac.localhost
#                 port_value: 9001
