admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901

node:
  id: id_1
  cluster: test

dynamic_resources:
  cds_config:
    path: /etc/envoy/cds.yaml
  lds_config:
    path: /etc/envoy/lds.yaml

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 8081
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.local_ratelimit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http_local_rate_limiter
          # - name: envoy.filters.http.wasm
          #   typed_config:
          #     "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          #     config:
          #       name: "my_plugin"
          #       vm_config:
          #         runtime: "envoy.wasm.runtime.v8"
          #         code:
          #           local:
          #             filename: "/etc/envoy/plugins/envoy_wasm_filter.wasm"
          #         allow_precompiled: true
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                ---Comment
              source_codes:
                accesslog.lua:
                  filename: /etc/envoy/plugins/accesslog.lua
                limit-response-rewrite.lua:
                  filename: /etc/envoy/plugins/limit-response-rewrite.lua
                
          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: saltbo
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: saltbo.cn
                  cluster: saltbo
              typed_per_filter_config:
                envoy.filters.http.local_ratelimit:
                  "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                  type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                  value:
                    stat_prefix: http_local_rate_limiter
                    token_bucket:
                      max_tokens: 10
                      tokens_per_fill: 10
                      fill_interval: 60s
                    filter_enabled:
                      runtime_key: local_rate_limit_enabled
                      default_value:
                        numerator: 100
                        denominator: HUNDRED
                    filter_enforced:
                      runtime_key: local_rate_limit_enforced
                      default_value:
                        numerator: 100
                        denominator: HUNDRED
                    response_headers_to_add:
                      - append: true
                        header:
                          key: x-local-rate-limit
                          value: 'true'
                envoy.filters.http.lua:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                  name: limit-response-rewrite.lua
# 2021-09-07T09:47:08.911+08:00
  
  clusters:
  - name: saltbo
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: saltbo
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: host.lima.internal
                port_value: 8000

                  
# dynamic_resources:
#   cds_config:
#     api_config_source:
#       api_type: GRPC
#       grpc_services:
#         envoy_grpc:
#           cluster_name: xds_cluster
#   lds_config:
#     api_config_source:
#       api_type: GRPC
#       grpc_services:
#         envoy_grpc:
#           cluster_name: xds_cluster
# static_resources:
#   clusters:
#   - name: xds_cluster
#     connect_timeout: 0.25s
#     type: STRICT_DNS
#     lb_policy: ROUND_ROBIN
#     http2_protocol_options: {}
#     load_assignment:
#       cluster_name: xds_cluster
#       endpoints:
#       - lb_endpoints:
#         - endpoint:
#             address:
#               socket_address:
#                 address: docker.for.mac.localhost
#                 port_value: 9001
